### PR TITLE
fix tsdb series not effect

### LINKED ISSUE #371: 数据同步到 TsDB 中序列名称错误
### logkit 相关配置:

image

### 预期表现:

数据同步到 TsDB 中，仓库名称为 ``cloud_buy`` 序列名称为 ``pet_order``

### 实际情况:

数据同步到 TsDB 中，仓库名称为 ``cloud_buy`` 序列名称为 ``cloud_buy``

image

### PR DESCRIPTION
**Pull request by wonderflow**
## Changes

fixes #371

## Reviewers

  - [ ] @[someone] please review
  - [ ] @[someotherone] please review

## Wiki Changes
 
  - options1...
  - options2...
    
## Checklist
   
   - [ ] Rebased/mergable
   - [ ] Tests pass
   - [ ] Wiki updated

### CODE REVIEW

File: reader/autofile.go [hunk 1]
```diff
@@ -6,6 +6,11 @@ import (
 	"path/filepath"
 	"strings"
 
+	"io/ioutil"
```
Comment (andrewei1316) [inline reader/autofile.go]: go fmt

File: sender/pandora_sender.go [hunk 2]
```diff
@@ -209,7 +209,7 @@ func NewPandoraSender(conf conf.MapConf) (sender Sender, err error) {
 
 	enableTsdb, _ := conf.GetBoolOr(KeyPandoraEnableTSDB, false)
 	tsdbReponame, _ := conf.GetStringOr(KeyPandoraTSDBName, repoName)
-	tsdbSeriesName, _ := conf.GetStringOr(KeyPandoraTSDBName, repoName)
+	tsdbSeriesName, _ := conf.GetStringOr(KeyPandoraTSDBSeriesName, repoName)
```
Comment (andrewei1316) [inline sender/pandora_sender.go]: 默认值改成 `tsdbReponame`

**Comment by andrewei1316** [comment]
LGTM

**Comment by andrewei1316** [comment]
LGTM
